version: '3.1'
services:
  myapp:
    build: .
    image: myapp
    command: gunicorn --bind  0.0.0.0:5000 wsgi:application
    expose:
      - 5000

  myapp-tests:
    image: myapp
    command: python main_test.py
    environment:
      APP_URL: http://myapp:5000
    depends_on:
      - myapp